### ISSUE TITLE
Infinite recursive call in `asdf list golang`

### ISSUE THREAD

**Issue by thinca** [kennyp/asdf-golang#83] opened 2022-06-30 16:27 UTC
**Describe the bug**
https://github.com/asdf-vm/asdf/pull/762
Since this change of asdf core, `asdf list golang` may call `parse-legacy-file` script internally.
[`parse-legacy-file`](https://github.com/kennyp/asdf-golang/blob/cc8bc47d4877beed61e10815d46669e1eaaa0bbe/bin/parse-legacy-file) script invokes `asdf list golang`.
The result is an infinite recursive call.

**To Reproduce**
1. Install head version of `asdf`
2. `mkdir example; cd example; go mod init example.com/m`
3. `asdf list golang`
4. Command hung(infinite recursive call).

**Expected behavior**
Show the version and exit.

**Desktop (please complete the following information):**
 - OS: Linux
 - asdf version: v0.10.2-624aede
 - asdf-golang cc8bc47d4877beed61e10815d46669e1eaaa0bbe

**Comment by yokonao** [comment] 2022-11-05 04:08
@kennyp 
Hi! I'm sorry to bother you when you're busy.

This issue is critical for asdf users which' enable legacy_version_file.
One solution is to revert #34 . Another is listing installed versions independent from `asdf list` command (a little complex and redundant).

I would like to work on solving this problem, so please let me know the desired solution!

**Comment by kennyp** [comment] 2022-11-06 20:03
@yokonao I'm using `asdf` version `v0.10.2-7e7a1fa` and I can't reproduce. :thinking: 

I'm working on pulling out the recursive call back into `asdf list`, but it would be great to reproduce before saying I've fixed it if that makes sense.

**Comment by yokonao** [comment] 2022-11-07 00:23
@kennyp 
[This PR](https://github.com/asdf-vm/asdf/pull/762) is merged after released v0.10.2. So, it makes sense that You are unable to reproduce when `v0.10.2-7e7a1fa`.
Howerver, this problem occurs if v0.10.3 is released in the future.

Please try to reproduce using latest `asdf`.

**Comment by kennyp** [comment] 2022-11-18 17:59
Ahh, I missed the note that you were using `asdf` head. Let me see what I can figure out.

**Comment by elementalvoid** [comment] 2022-12-03 22:26
I'll note that I _did_ experience this. But I am no longer able to after ensuring everything was up to date.

I updated `asdf` and the plugin:
```sh
$ asdf update
$ asdf plugin update golang
```

After which, I'm no longer able to replicate.

---

Looking at my `git reflog` for both the plugin and asdf, I was able to reset my installation to a reproducible configuration!

According to my `reflog`, I've had version cc8bc47 of the plugin the whole time (recently deleted it and reinstalled it for other reasons).

But for `asdf`, this update took me from https://github.com/asdf-vm/asdf/commit/cd31d57 (can reproduce) to https://github.com/asdf-vm/asdf/commit/7e7a1fa (cannot reproduce).


```
$ cd ~/.asdf
$ git checkout cd31d57
```

And 💥 recursion bug. Hopefully that helps!

**Comment by dushyantss** [comment] 2022-12-16 07:44
asdf version 0.11.0 is out and after updating my local setup I can confirm facing this bug.

Note: this bug has been the cause for issues like `bash warning shell level (1000) too high resetting to 1`(got this when simply cd'ing into a go project) and `"fork failed: Resource temporarily unavailable"`(got this after running the gopls server for a while in neovim).

**Comment by jharley** [comment] 2022-12-16 21:07
+1 to @dushyantss is reporting above

**Comment by jharley** [comment] 2022-12-16 21:20
I just tried the regex fix in #89 and it seems to have helped

**Comment by kennyp** [comment] 2022-12-16 21:53
I'm trying to resolve this on the [issue](https://github.com/asdf-vm/asdf/issues/1372) I opened on asdf as I need a way to get a list of the currently installed versions to accurately conform to `go.mod`.

**Comment by kennyp** [comment] 2022-12-17 04:19
@yokonao, @dushyantss, or @jharley can y'all verify that #93 fixes the issue for you?

**Comment by dushyantss** [comment] 2022-12-17 04:30
Tested #93, works for me 🥳. Tried both, cd'ing into a go project and opening it in neovim with gopls.

Thanks @kennyp for the prompt fix.

**Comment by kennyp** [comment] 2022-12-17 04:42
Awesome! I'll merge it.

**Closed** 2022-12-17 04:43 UTC

**Comment by jharley** [comment] 2022-12-17 15:05
#93 fixed things for me as well!

Thanks for the quick resolution, @kennyp!
