### ISSUE TITLE
godoc not properly linked in new version 1.14.6 (after installation)

### ISSUE THREAD

**Issue by AxelRHD** [kennyp/asdf-golang#36] opened 2020-08-05 12:21 UTC
**Describe the bug**
I just installed GO version 1.14.6 with asdf. After that (and installing godoc manually, because it is no longer default in installation) the function `godoc` does not work anymore. I get the following message:

> asdf: No preset version installed for command godoc
> Please install the missing version by running one of the following:
> 
> asdf install golang 1.14.6
> 

**To Reproduce**
1. `asdf install golang 1.14.6`
2. `asdf global golang 1.14.6`
3. `go get golang.org/x/tools/cmd/godoc`
4. `asdf reshim golang`
5. `godoc help` (just for testing)

**Expected behavior**
Execute installed `godoc`.

**Server (please complete the following information):**
 - OS: Ubuntu Server 18.04.4 LTS

**Comment by kennyp** [comment] 2020-12-08 18:51
Hmm, I can't reproduce. I followed the same steps and `godoc` works as expected. What does your `go env` look like? And are you using the latest version of `asdf` and the plugin?

**Comment by dreyescat** [comment] 2020-12-25 19:37
In case it is helpful...

I had the same *issue*. It was because I changed the `GOBIN` environment variable to point to a personal `~/bin` folder but forgot to add this folder to the `$PATH`.

Running `go get golang.org/x/tools/cmd/godoc` installed the `godoc` binary in my personal `~/bin` folder instead of the default `.asdf` one. So it was not _accessible_ because such folder was not in the `$PATH`.

Make sure you have the `GOBIN` path in your `$PATH`.

```bash
go env GOBIN
```

Once added to the `$PATH` it worked perfectly.

**Comment by slewsys** [comment] 2021-04-13 07:48
_asdf-golang_ is working correctly for me too (Ubuntu and Fedora).  The critical step appears to `asdf reshim golang` since installed utilities initially don't appear in the _~/.asdf/shim_ directory.

**Comment by kennyp** [comment] 2021-05-12 17:54
I'm not sure that there's anything else to do to totally prevent other people from running into this issue. Any ideas, or maybe I'll just close this for now?

**Comment by slewsys** [comment] 2021-05-15 08:17
Yeah, just wanted to document the issue.  Thanks!

**Comment by kennyp** [comment] 2021-05-15 12:40
👍

**Closed by kennyp** 2021-05-15 12:40 UTC

**Comment by relaxdiego** [comment] 2023-05-11 03:15
Step 3 works for me if it's `go install golang.org/x/tools/cmd/godoc@latest`
